---
  - name: Install apt requirements
    become: yes
    apt: 
      pkg: aptitude
      state: present

  - name: Run the equivalent of "apt-get update && apt-get upgrade" as a separate step
    become: true  #new syntax to sudo
    apt:
      update_cache: yes
      upgrade: yes
      cache_valid_time: 3600

  - name: Save name of machine
    shell: uname -r
    register: uname

  - name: Install linux-image extra for Docker aufs storage driver
    become: true
    apt: name={{item}} state=present
    with_items:
      - linux-image-extra-{{uname.stdout}}
      - linux-image-extra-virtual

  - name: Install packages to allow apt to use a repository over HTTPS for docker
    become: true
    apt: name={{item}} state=present
    with_items:
      - curl 
      - apt-transport-https
      - ca-certificates
      - software-properties-common

  - name: Add docker gpg key
    become: true
    apt_key: 
      url: "https://apt.dockerproject.org/gpg"
      id: 58118E89F3A912897C070ADBF76221572C52609D
      state: present

  - name: Add docker apt repository
    become: true
    apt_repository: 
      repo: "deb https://apt.dockerproject.org/repo {{ ansible_distribution|lower }}-{{ ansible_distribution_release }} main" 
      state: present

  - name: Install docker-engine
    become: true
    apt:
      update_cache: yes
      pkg: docker-engine #TODO: pin this to latest version once live
      state: present  